matrimony/accounts/urls.py
from django.urls import path
from .views import *
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', user_registration, name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),


    path('basic_info/', basic_info_view, name='basic_info'),
    path('lifestyle_info/', lifestyle_view, name='lifestyle_info'),
    path('employment_info/', employment_status_view, name='employment_status'),
    path('relationship_info/', relationship_type_view, name='relationship_type'),
    
]

matrimony/matrimony/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('user.urls', namespace='user')),
    path('MatrimonyApp/',include('matrimonyApp.urls', namespace='matrimonyApp')),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matrimony/matrimonyApp/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'matrimonyApp'
urlpatterns = [

    path('home/', HomeView.as_view(), name='home'),

    path('parents_details/', parents_details_view, name='parents_details'),
    path('partner_preference/', views.partner_preference_view, name='partner_preference'),

    path('suggestions/',SuggestionView.as_view(), name='suggestions'),

    path('save_profile/<int:profile_id>/', save_profile, name='save_profile'),
    path('saved_profiles/', saved_profiles, name='saved_profiles'),

    path('exclude_profile/<int:profile_id>/', ExcludeProfileView.as_view(), name='exclude_profile'),


    path('send_request/<int:profile_id>/', views.send_request, name='send_request'),
    
    path('respond_to_request/<int:request_id>/<str:action>/', views.respond_to_request, name='respond_to_request'),
    path('view_requests/', views.view_requests, name='view_requests'),
    path('unfriend/<int:user_id>/', views.unfriend, name='unfriend'),
    path('friends_list/', FriendsListView.as_view(), name='friends_list'),

    path('send_message/<int:recipient_id>/', send_message, name='send_message'),
    path('chat/<int:friend_id>/', chat_room, name='chat_room'),
    
    path('chat/', views.chat_with_friends, name='chat_with_friends'),
    path('chat/<str:room_name>/', views.chat_with_friends, name='chat_with_friends'),
    
    
    path('freechat/', views.ChatWithFriendsView, name='chat_with_free_friends'),
    path('freechat/<str:room_name>/', views.ChatWithFriendsView, name='chat_with_free_friends'),

    path('profile/<int:profile_id>/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('myprofile/', views.MyProfileView.as_view(), name='my_profile_detail'),

    path('subscription/', SubscriptionView.as_view(), name='subscription'),
    

    

    path('webhook/',stripe_webhook,name='stripe-webhook'),

    path('successPremium/<str:checkout_session_id>/', views.SuccessPremiumView.as_view(), name='success'),
    path('successBasic/<str:checkout_session_id>/', views.SuccessBasicView.as_view(), name='success'),

    path('cancel/', CancelView.as_view(), name='cancel'),

    
]

matrimony/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'
urlpatterns = [
    path('', HomeView.as_view(), name='home'), 
]

matrimony/templates/shared/base.html
<!doctype html>
<html lang="en">

<head>
    
    {% block meta %}
        
    {% endblock meta %}
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <!-- Bootstrap CSS v5.2.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />

    {% block styles %}
        
    {% endblock styles %}
        
</head>

<body>
    <header>
        {% include 'shared/navbar.html' %}
    </header>
    <main>
        
        {% block content %}
            
        {% endblock content %}
            
    </main>
    <footer>
        <!-- place footer here -->
    </footer>
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    
    {% block scripts %}
        
    {% endblock scripts %}
        
</body>

</html>

matrimony/templates/shared/matrimonybase.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %}
    {% endblock meta %}

    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS v5.2.1 -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />

    <!-- animate__animated CSS -->
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
     {% load static %}
     <link rel="icon" href="{% static 'MatrimonyApp.ico' %}" type="image/x-icon">
    <!-- style.CSS file -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block styles %}
    
    {% endblock styles %}
  </head>

  <body>
    <header>{% include 'shared/matrimonynavbar.html' %}</header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
      <!-- place footer here -->
    </footer>
    <!-- Bootstrap JavaScript Libraries -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>

    {% block scripts %}
    
    {% endblock scripts %}
  </body>
</html>

matrimony/templates/shared/matrimonynavbar.html
<nav class="navbar navbar-expand-lg" style="background-color: orange">
  <div class="container-fluid">
    <a class="navbar-brand h1 mb-0" href="#">MATRIMONY APP</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item me-2">
          <a class="nav-link" style="color: black" aria-current="page" href="{% url 'matrimonyApp:home' %}">Home</a>
        </li>
        <li class="nav-item me-2">
          <a class="nav-link" style="color: black" href="{% url 'matrimonyApp:suggestions' %}">Suggestions</a>
        </li>
        <li class="nav-item me-2">
          <a class="nav-link" style="color: black" href="{% url 'matrimonyApp:subscription' %}">Pricing</a>
        </li>
      </ul>
    </div>
    <button class="btn btn-outline-dark ms-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">Menu</button>
  </div>
</nav>

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    <h5 class="offcanvas-title" id="offcanvasRightLabel">Menu</h5>
  </div>
  

  <div class="card mx-3">
    <div class="card-body text-end">
      {{ subscription_type }}
    </div>
  </div>
  <div class="offcanvas-body d-flex flex-column">
    <div class="flex-grow-1">
      <div class="row ms-1">
        <div class="list-group text-end" id="list-tab" role="tablist">
          <a class="list-group-item list-group-item-action list-group-item-light" href="{% url 'matrimonyApp:my_profile_detail' %}">MY Profile</a>
          {% if has_subscription %}
          <a class="list-group-item list-group-item-action list-group-item-light" href="{% url 'matrimonyApp:chat_with_friends' %}">Message</a>
          {% else %}
          <a class="list-group-item list-group-item-action list-group-item-light" href="{% url 'matrimonyApp:chat_with_free_friends' %}">Free Message</a>
          {% endif %}
          <a class="list-group-item list-group-item-action list-group-item-light" href="{% url 'matrimonyApp:friends_list' %}">Friends List</a>
          <a class="list-group-item list-group-item-action list-group-item-light" href="{% url 'matrimonyApp:view_requests' %}">View Request</a>
          <a class="list-group-item list-group-item-action list-group-item-light" href="{% url 'matrimonyApp:saved_profiles' %}">Saved Profiles</a>
          {% if has_subscription %}
          <a class="list-group-item list-group-item-action list-group-item-light" href="https://billing.stripe.com/p/login/test_aEU5mp29x635eeA289">Billing</a>
          {% endif %}
          <a class="list-group-item list-group-item-action list-group-item-light" href="{% url 'accounts:profile' %}">Accounts Settings</a>
          <a class="list-group-item list-group-item-action list-group-item-light" href="{% url 'matrimonyApp:parents_details' %}">personal Details</a>
          <a class="list-group-item list-group-item-action list-group-item-light" href="{% url 'matrimonyApp:partner_preference' %}">Preference</a>
          <a class="list-group-item list-group-item-action list-group-item-light" href="{% url 'accounts:relationship_type' %}">Switch Account</a>
        </div>
      </div>
    </div>
    <div>
      <div class="list-group text-color-red text-end">
        <a href="{% url 'accounts:logout' %}" class="list-group-item list-group-item-action list-group-item-light" style="color: red">Logout</a>
      </div>
    </div>
  </div>
  

matrimony/templates/shared/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-secondary">
    <div class="container">
        <a class="navbar-brand" href="#">3-IN-1-APP</a>
        <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse"
            data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
                
                
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                {% endif %}
                    
            </ul>
            

            {% if user.is_authenticated %}
            <ul class="navbar-nav ms-auto mt-2 mt-lg-0 me-2">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Profile
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a></li>
                      <li><a class="dropdown-item" href="#">Change Password</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                    </ul>
                  </li>
            </ul>
            {% endif %}
                
            <form class="d-flex my-2 my-lg-0">
                
            </form>
        </div>
    </div>
</nav>