matrimony/matrimony/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('user.urls', namespace='user')),
    path('MatrimonyApp/',include('matrimonyApp.urls', namespace='matrimonyApp')),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matrimony/matrimonyApp/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'matrimonyApp'
urlpatterns = [

    path('home/', HomeView.as_view(), name='home'),

    path('parents_details/', parents_details_view, name='parents_details'),
    path('partner_preference/', views.partner_preference_view, name='partner_preference'),

    path('suggestions/',SuggestionView.as_view(), name='suggestions'),

    path('save_profile/<int:profile_id>/', save_profile, name='save_profile'),
    path('saved_profiles/', saved_profiles, name='saved_profiles'),

    path('exclude_profile/<int:profile_id>/', ExcludeProfileView.as_view(), name='exclude_profile'),


    path('send_request/<int:profile_id>/', views.send_request, name='send_request'),
    
    path('respond_to_request/<int:request_id>/<str:action>/', views.respond_to_request, name='respond_to_request'),
    path('view_requests/', views.view_requests, name='view_requests'),
    path('unfriend/<int:user_id>/', views.unfriend, name='unfriend'),
    path('friends_list/', FriendsListView.as_view(), name='friends_list'),

    path('send_message/<int:recipient_id>/', send_message, name='send_message'),
    path('chat/<int:friend_id>/', chat_room, name='chat_room'),
    
    path('chat/', views.chat_with_friends, name='chat_with_friends'),
    path('chat/<str:room_name>/', views.chat_with_friends, name='chat_with_friends'),
    
    
    path('freechat/', views.ChatWithFriendsView, name='chat_with_free_friends'),
    path('freechat/<str:room_name>/', views.ChatWithFriendsView, name='chat_with_free_friends'),

    path('profile/<int:profile_id>/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('myprofile/', views.MyProfileView.as_view(), name='my_profile_detail'),

    path('subscription/', SubscriptionView.as_view(), name='subscription'),
    

    

    path('webhook/',stripe_webhook,name='stripe-webhook'),

    path('successPremium/<str:checkout_session_id>/', views.SuccessPremiumView.as_view(), name='success'),
    path('successBasic/<str:checkout_session_id>/', views.SuccessBasicView.as_view(), name='success'),

    path('cancel/', CancelView.as_view(), name='cancel'),

    
]

matrimony/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'
urlpatterns = [
    path('', HomeView.as_view(), name='home'), 
]

matrimony/matrimonyApp/forms.py
from django import forms
from django.forms import Form,IntegerField
from .models import ParentsDetails, PartnerPreference,FriendRequest,Message



class ParentsDetailsForm(forms.ModelForm):
    class Meta:
        model = ParentsDetails
        fields = [
            'father_name', 'father_occupation',
            'mother_name', 'mother_occupation', 
            'siblings_count',
            'annual_income',
            'permanent_address', 'present_address',
            'country', 'state', 'district', 
            'height', 'weight',
            'caste', 'religion',
            'zodiac_sign', 'horoscope',
            'interested_gender',
        ]
        widgets = {
            'father_name': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'father_occupation': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'mother_name': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'mother_occupation': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'siblings_count': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'annual_income': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'permanent_address': forms.Textarea(attrs={'class': 'form-control', 'required': 'true','rows': 3}),
            'present_address': forms.Textarea(attrs={'class': 'form-control', 'required': 'true','rows': 3}),
            'country': forms.Select(attrs={'class': 'form-control', 'required': 'true'}),
            'state': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Select', 'required': 'true'}),
            'district': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Select', 'required': 'true'}),
            'height': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'weight': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'caste': forms.Select(attrs={'class': 'form-control', 'required': 'true', 'placeholder': 'Select'}),
            'religion': forms.Select(attrs={'class': 'form-control', 'required': 'true', 'placeholder': 'Select'}),
            'zodiac_sign': forms.Select(attrs={'class': 'form-control', 'required': 'true', 'placeholder': 'Select'}),
            'horoscope': forms.FileInput(attrs={'class': 'form-control', 'required': 'true'}),
            'interested_gender': forms.Select(attrs={'class': 'form-control', 'required': 'true', 'placeholder': 'Select'}),
        }

class PartnerPreferenceForm(forms.ModelForm):
    class Meta:
        model = PartnerPreference
        fields = [
            'age_min', 'age_max', 'caste', 'religion', 'height_min', 
            'height_max', 'weight_min', 'weight_max', 'income_min', 'income_max', 
            'qualification'
        ]
        widgets = {
            'age_min': forms.NumberInput(attrs={'class': 'form-control'}),
            'age_max': forms.NumberInput(attrs={'class': 'form-control'}),
            'caste': forms.Select(attrs={'class': 'form-control'}),
            'religion': forms.Select(attrs={'class': 'form-control'}),
            'height_min': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'height_max': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'weight_min': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'weight_max': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'income_min': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'income_max': forms.NumberInput(attrs={'class': 'form-control', 'required': 'true'}),
            'qualification': forms.Select(attrs={'class': 'form-control', 'required': 'true'}),
        }

class FriendRequestForm(forms.ModelForm):
    class Meta:
        model = FriendRequest
        fields = ['to_user']

class SaveProfileForm(forms.Form):
    pass

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={'rows': 2, 'placeholder': 'Type your message here...'}),
        }

matrimony/matrimonyApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView,FormView,ListView
from .forms import ParentsDetailsForm,PartnerPreferenceForm,FriendRequestForm,MessageForm,SaveProfileForm
from django.contrib.auth.decorators import login_required
from .models import ParentsDetails,PartnerPreference,FriendRequest,ProfileExclusion,Message,Subscription,PaymentDetail, SavedProfile
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.models import User
from django.db.models import Q,Max,F, Case, When, DateTimeField
from django.views import View
from django.urls import reverse

from django.http import JsonResponse
import json
import stripe
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.http import HttpResponse
from django.conf import settings
# from django.utils.decorators import method_decorator
# from django.urls import reverse_lazy


# Create your views here.


# Create your views here.

class HomeView(LoginRequiredMixin,TemplateView):
    template_name = 'home.html'

@login_required
def parents_details_view(request):
    try:
        parents_details = request.user.parents_details
    except ParentsDetails.DoesNotExist:
        parents_details = ParentsDetails(user=request.user)

    if request.method == 'POST':
        form = ParentsDetailsForm(request.POST, request.FILES, instance=parents_details)
        if form.is_valid():
            form.save()
            return redirect('matrimonyApp:partner_preference')
    else:
        form = ParentsDetailsForm(instance=parents_details)
    
    return render(request, 'parents_details_form.html', {'form': form})

@login_required
def partner_preference_view(request):
    try:
        partner_preference = request.user.partner_preference
    except PartnerPreference.DoesNotExist:
        partner_preference = None

    if request.method == 'POST':
        form = PartnerPreferenceForm(request.POST, instance=partner_preference)
        if form.is_valid():
            partner_preference = form.save(commit=False)
            partner_preference.user = request.user
            partner_preference.save()
            return redirect('matrimonyApp:home')
    else:
        form = PartnerPreferenceForm(instance=partner_preference)

    context = {'form': form}
    return render(request, 'partner_preference_form.html', context)

class SuggestionView(LoginRequiredMixin, TemplateView):
    template_name = 'suggestions.html'

    def get_gender_filter(self, interested_gender):
        if interested_gender == 'MALE':
            return Q(gender='MALE')
        elif interested_gender == 'FEMALE':
            return Q(gender='FEMALE')
        else:
            return Q(gender__in=['MALE', 'FEMALE'])
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        try:
            partner_preference = user.partner_preference
            interested_gender = user.parents_details.interested_gender
            friends = FriendRequest.objects.filter(
                Q(from_user=user) | Q(to_user=user),
                status='accepted'
            ).values_list('from_user', 'to_user')
            friend_ids = [item for sublist in friends for item in sublist if item != user.id]
            gender_filter = self.get_gender_filter(interested_gender)
            profiles = User.objects.filter(
                age__gte=partner_preference.age_min,
                age__lte=partner_preference.age_max,
                parents_details__caste=partner_preference.caste,
                parents_details__religion=partner_preference.religion,
                parents_details__height__gte=partner_preference.height_min,
                parents_details__height__lte=partner_preference.height_max,
                parents_details__weight__gte=partner_preference.weight_min,
                parents_details__weight__lte=partner_preference.weight_max,
                parents_details__annual_income__gte=partner_preference.income_min,
                parents_details__annual_income__lte=partner_preference.income_max,
                education_level=partner_preference.qualification
            ).filter(gender_filter).exclude(id__in=friend_ids).exclude(id=user.id).select_related('partner_preference').prefetch_related('parents_details')
            context['profiles'] = profiles
        except PartnerPreference.DoesNotExist:
            context['profiles'] = User.objects.none()

        return context

@login_required
def send_request(request, profile_id):
    to_user = get_object_or_404(User, id=profile_id)
    from_user = request.user
    if request.method == 'POST':
        if not FriendRequest.objects.filter(from_user=from_user, to_user=to_user).exists():
            FriendRequest.objects.create(from_user=from_user, to_user=to_user)
    return redirect('matrimonyApp:suggestions')

@login_required
def respond_to_request(request, request_id, action):
    friend_request = get_object_or_404(FriendRequest, id=request_id, to_user=request.user)
    
    if action == 'accept':
        friend_request.status = 'accepted'
    elif action == 'reject':
        friend_request.status = 'rejected'
    friend_request.save()
    
    return redirect('matrimonyApp:view_requests')

@login_required
def view_requests(request):
    received_requests = FriendRequest.objects.filter(to_user=request.user, status='pending')
    sent_requests = FriendRequest.objects.filter(from_user=request.user, status='pending')
    
    context = {
        'received_requests': received_requests,
        'sent_requests': sent_requests,
    }
    
    return render(request, 'requests.html', context)

class FriendsListView(LoginRequiredMixin, ListView):
    template_name = 'friends_list.html'
    context_object_name = 'friends'

    def get_queryset(self):
        return FriendRequest.objects.filter(
            Q(from_user=self.request.user) | Q(to_user=self.request.user),
            status='accepted'
        ).select_related('from_user', 'to_user')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Check if the user has an active, paid plan
        has_active_paid_plan = PaymentDetail.objects.filter(
            user=self.request.user,
            status='active',
            payment_status='paid'
        ).exists()
        context['has_active_paid_plan'] = has_active_paid_plan
        return context

@login_required
def save_profile(request, profile_id):
    profile = get_object_or_404(User, id=profile_id)
    saved_profile, created = SavedProfile.objects.get_or_create(user=request.user, saved_profile=profile)
    if created:
        saved_profile.save()
    return redirect('matrimonyApp:suggestions')

@login_required
def saved_profiles(request):
    saved_profiles = SavedProfile.objects.filter(user=request.user).select_related('saved_profile', 'saved_profile__parents_details')
    return render(request, 'saved_profiles.html', {'saved_profiles': saved_profiles})

@login_required
def unfriend(request, user_id):
    # friend_request = get_object_or_404(FriendRequest, from_user=request.user, to_user__id=user_id, status='accepted')
    friend_request = FriendRequest.objects.filter(
        Q(from_user=request.user, to_user_id=user_id, status='accepted') |
        Q(from_user_id=user_id, to_user=request.user, status='accepted')
    ).first()
    friend_request.unfriend()
    return redirect('matrimonyApp:friends_list')  # Redirect to your friends list page

class ExcludeProfileView(LoginRequiredMixin, View):
    def post(self, request, profile_id):
        profile = get_object_or_404(User, id=profile_id)
        exclusion, created = ProfileExclusion.objects.get_or_create(user=request.user, excluded_profile=profile)
        return redirect('matrimonyApp:suggestions')

@login_required
def send_message(request, recipient_id):
    recipient = get_object_or_404(User, id=recipient_id)
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = request.user
            message.recipient = recipient
            message.save()
            return redirect('matrimonyApp:chat_room', friend_id=recipient.id)
    else:
        form = MessageForm(initial={'recipient': recipient})
    return render(request, 'send_message.html', {'form': form, 'recipient': recipient})

@login_required
def chat_room(request, friend_id):
    friend = get_object_or_404(User, id=friend_id)
    messages = Message.objects.filter(
        Q(sender=request.user, recipient=friend) | Q(sender=friend, recipient=request.user)
    ).order_by('timestamp')
    
    user = request.user
    friends = FriendRequest.objects.filter(
        Q(from_user=user, status='accepted') | Q(to_user=user, status='accepted')
    )

    if request.method == 'POST':
        body = request.POST.get('body')
        if body:
            Message.objects.create(sender=request.user, recipient=friend, body=body)
            return redirect('matrimonyApp:chat_room', friend_id=friend.id)

    return render(request, 'chat_room.html', {'friend': friend, 'messages': messages, 'friends': friends})

def chat_with_friends(request, room_name=None):
    user = request.user
    friends = FriendRequest.objects.filter(
        Q(from_user=user, status='accepted') | Q(to_user=user, status='accepted')
    )
    
    friends_with_last_message = friends.annotate(
        last_message_time=Max('to_user__received_messages__timestamp')
    ).order_by('-last_message_time')
 
    friend = None
    messages = []
    if room_name:
        friend = get_object_or_404(User, username=room_name)
        messages = Message.objects.filter(
            (Q(sender=user) & Q(recipient=friend)) |
            (Q(sender=friend) & Q(recipient=user))
        ).order_by('timestamp')
        
    

matrimony/matrimonyApp/templates/cancel.html
{% extends 'shared/matrimonybase.html' %}
{% block content %}
<h1>Payment Cancelled</h1>
<p>Your payment was cancelled. Please try again.</p>
{% endblock %}

matrimony/matrimonyApp/templates/chat_with_free_friends.html
<!-- templates/chat_with_friends.html -->
{% extends 'shared/matrimonybase.html' %}
{% block content %}
<style>
    .chat-page {
        display: flex;
        height: 80vh;
    }
    .friends-list {
        width: 20%;
        border-right: 1px solid #ddd;
        overflow-y: auto;
        padding: 10px;
    }
    .friends-list h3 {
        margin-top: 0;
    }
    .friends-list a {
        display: flex;
        align-items: center;
        padding: 10px;
        border-radius: 5px;
        text-decoration: none;
        color: black;
        margin-bottom: 5px;
        background-color: #f9f9f9;
    }
    .friends-list a:hover {
        background-color: #e9e9e9;
    }
    .friends-list img {
        border-radius: 50%;
        margin-right: 10px;
        width: 40px;
        height: 40px;
    }
    .chat-container {
        justify-content: center;
        display: flex;
        flex-direction: column;
        flex: 1;
        padding: 10px;
    }
    #chat-box {
        flex: 1;
        overflow-y: auto;
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 5px;
        margin-bottom: 10px;
        background-color: #f9f9f9;
    }
    .message {
        margin-bottom: 10px;
        padding: 10px;
        border-radius: 8px;
        max-width: 100%;
        word-wrap: break-word;
    }
    .message.sent {
        background-color: #007bff;
        color: white;
        align-self: flex-end;
        text-align: right;
    }
    .message.received {
        background-color: #e1e1e1;
        align-self: flex-start;
    }
    .chat-input-container {
        display: flex;
        align-items: center;
    }
    .chat-input-container textarea {
        flex: 1;
        resize: none;
        border-radius: 5px;
        border: 1px solid #ccc;
        padding: 10px;
        margin-right: 10px;
    }
    .chat-input-container button {
        padding: 10px 20px;
    }
    .text {
        font-size: xx-large;
    }
</style>

<div class="chat-page">
    <div class="friends-list">
        <h3>Your Friends</h3>
        {% for friend in friends %}
        <a href="{% url 'matrimonyApp:chat_with_free_friends' room_name=friend.username %}">
            <img src="{{ friend.profile_pic.url }}" alt="{{ friend.get_full_name }}'s profile image">
            {{ friend.get_full_name }}
        </a>        
        {% endfor %}
    </div>
    <div class="chat-container">
        {% if friend %}
        <h2>Chat with {{ friend.get_full_name }}</h2>
        <div id="chat-box">
            {% for message in messages %}
            <div class="message {% if message.sender == request.user %}sent{% else %}received{% endif %}">
                <strong>{{ message.sender.get_full_name }}:</strong> {{ message.body }}
            </div>
            {% endfor %}
        </div>
        <form method="post" class="chat-input-container">
            {% csrf_token %}
            <textarea name="body" placeholder="Type your message here" rows="3" required></textarea>
            <button type="submit" class="btn btn-outline-primary">Send</button>
        </form>
        {% else %}
        <p class="text text-center">Buy a Subscription to start chatting.</p>
        <p class="text text-center">limited Access chat Now...</p>
        {% endif %}
    </div>
</div>
{% endblock %}

matrimony/matrimonyApp/templates/chat_with_friends.html
<!-- templates/chat_with_friends.html -->
{% extends 'shared/matrimonybase.html' %}
{% block content %}
<style>
    .chat-page {
        display: flex;
        height: 80vh;
    }
    .friends-list {
        width: 20%;
        border-right: 1px solid #ddd;
        overflow-y: auto;
        padding: 10px;
    }
    .friends-list h3 {
        margin-top: 0;
    }
    .friends-list a {
        display: flex;
        align-items: center;
        padding: 10px;
        border-radius: 5px;
        text-decoration: none;
        color: black;
        margin-bottom: 5px;
        background-color: #f9f9f9;
    }
    .friends-list a:hover {
        background-color: #e9e9e9;
    }
    .friends-list img {
        border-radius: 50%;
        margin-right: 10px;
        width: 40px;
        height: 40px;
    }
    .chat-container {
        justify-content: center;
        display: flex;
        flex-direction: column;
        flex: 1;
        padding: 10px;
    }
    #chat-box {
        flex: 1;
        overflow-y: auto;
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 5px;
        margin-bottom: 10px;
        background-color: #f9f9f9;
    }
    .message {
        margin-bottom: 10px;
        padding: 10px;
        border-radius: 8px;
        max-width: 100%;
        word-wrap: break-word;
    }
    .message.sent {
        background-color: #007bff;
        color: white;
        align-self: flex-end;
        text-align: right;
    }
    .message.received {
        background-color: #e1e1e1;
        align-self: flex-start;
    }
    .chat-input-container {
        display: flex;
        align-items: center;
    }
    .chat-input-container textarea {
        flex: 1;
        resize: none;
        border-radius: 5px;
        border: 1px solid #ccc;
        padding: 10px;
        margin-right: 10px;
    }
    .chat-input-container button {
        padding: 10px 20px;
    }
    .text {
        font-size: xx-large;
    }
</style>

<div class="chat-page">
    <div class="friends-list">
        <h3>Your Friends</h3>
        <!-- <ul> -->
            {% for friend in friends %}
                {% if friend.from_user == request.user %}
                <!-- <li> -->
                    <a href="{% url 'matrimonyApp:chat_with_friends' room_name=friend.to_user.username %}">
                        <img src="{{ friend.to_user.profile_pic.url }}" alt="{{ friend.to_user.get_full_name }}'s profile image">
                        {{ friend.to_user.get_full_name }}
                    </a>
                <!-- </li> -->
                {% else %}
                <!-- <li> -->
                    <a href="{% url 'matrimonyApp:chat_with_friends' room_name=friend.from_user.username %}">
                        <img src="{{ friend.from_user.profile_pic.url }}" alt="{{ friend.from_user.get_full_name }}'s profile image">
                        {{ friend.from_user.get_full_name }}
                    </a>
                <!-- </li> -->
                {% endif %}
            {% endfor %}
        <!-- </ul> -->
    </div>
    <div class="chat-container">
        {% if friend %}
        <h2>Chat with {{ friend.get_full_name }}</h2>
        <div id="chat-box">
            {% for message in messages %}
            <div class="message {% if message.sender == request.user %}sent{% else %}received{% endif %}">
                <strong>{{ message.sender.get_full_name }}:</strong> {{ message.body }}
            </div>
            {% endfor %}
        </div>
        <form method="post" class="chat-input-container">
            {% csrf_token %}
            <textarea name="body" placeholder="Type your message here" rows="3" required></textarea>
            <button type="submit" class="btn btn-outline-primary">Send</button>
        </form>
        {% else %}
        <p class="text text-center">Select a friend to start chatting.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

matrimony/matrimonyApp/templates/friends_list.html
<!-- templates/friends_list.html -->
{% extends 'shared/matrimonybase.html' %}
{% block content %}
<h1>Your Friends</h1>
<ul style="list-style: none; padding: 0;">
    {% for friend in friends %}
    <li style="display: flex; align-items: center; justify-content: space-between; padding: 10px; border-bottom: 1px solid #ddd;">
        {% if friend.from_user == request.user %}
        <div style="display: flex; align-items: center; max-width: auto;">
            <img src="{{ friend.to_user.profile_pic.url }}" alt="{{ friend.to_user.get_full_name }}'s profile image" style="border-radius: 50%; width: 40px; height: 40px; margin-right: 10px;">
            <span>{{ friend.to_user.get_full_name }}</span>
        </div>
        <div>
            <form action="{% url 'matrimonyApp:unfriend' friend.to_user.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Unfriend</button>
            </form>
            <a href="{% url 'matrimonyApp:chat_room' friend.to_user.id %}" class="btn btn-primary">Chat</a>
            <a href="{% url 'matrimonyApp:profile_detail' profile_id=friend.to_user.id %}" class="btn btn-secondary">View Full Profile</a>
        </div>
        {% else %}
        <div style="display: flex; align-items: center; max-width: auto;">
            <img src="{{ friend.from_user.profile_pic.url }}" alt="{{ friend.from_user.get_full_name }}'s profile image" style="border-radius: 50%; width: 40px; height: 40px; margin-right: 10px;">
            <span>{{ friend.from_user.get_full_name }}</span>
        </div>
        <div>
            <form action="{% url 'matrimonyApp:unfriend' friend.from_user.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Unfriend</button>
            </form>
            {% if has_active_paid_plan %}
            <a href="{% url 'matrimonyApp:chat_room' friend.from_user.id %}" class="btn btn-primary">Chat</a>
            {% endif %}
            <a href="{% url 'matrimonyApp:profile_detail' profile_id=friend.from_user.id %}" class="btn btn-secondary">View Full Profile</a>
        </div>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% endblock %}

matrimony/matrimonyApp/templates/suggestions.html
<!-- templates/suggestions.html -->

{% extends 'shared/matrimonybase.html' %}
{% block content %}
<style>
    body {
        background-color: #000;
        color: #fff;
    }
</style>
{% if profiles %}
<div class="container mt-2">
    <div class="text mb-2 p-1">
        <h1 class="text-start animate__animated animate__fadeIn">Suggested Profiles</h1>
    </div>
    <div class="row">
        {% for profile in profiles %}
        <div class="col-md-4" style="width: 20%;">
            <div class="card mb-4 shadow-sm animate__animated animate__zoomIn">
                {% if profile.profile_pic %}
                <img src="{{ profile.profile_pic.url }}" class="card-img-top" style="object-fit: cover; width: 100%; height: 200px;" alt="{{ profile.get_full_name }}">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ profile.get_full_name }}</h5>
                    <p class="card-text">Age: {{ profile.age }}</p>
                    <p class="card-text">Location: {{ profile.parents_details.district }}</p>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#profileModal{{ profile.id }}">
                        View Profile
                    </button>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="profileModal{{ profile.id }}" tabindex="-1" aria-labelledby="exampleModalLabel{{ profile.id }}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header text-primary">
                        <h1 class="modal-title fs-5" id="exampleModalLabel{{ profile.id }}">{{ profile.get_full_name }}</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-dark">
                        <div class="row">
                            <div class="col-6">
                                <p class="card-text">Age: {{ profile.age }}</p>
                                <p class="card-text">Caste: {{ profile.parents_details.caste }}</p>
                                <p class="card-text">Religion: {{ profile.parents_details.religion }}</p>
                                <p class="card-text">Height: {{ profile.parents_details.height }} cm</p>
                                <p class="card-text">Weight: {{ profile.parents_details.weight }} kg</p>
                                <p class="card-text">Income: {{ profile.parents_details.annual_income }}</p>
                                <p class="card-text">Education: {{ profile.education_level }}</p>
                            </div>
                            <div class="col-6">
                                <img src="{{ profile.profile_pic.url }}" class="card-img-top" style="object-fit:cover; width: 200px;; height: 200px;" alt="{{ profile.get_full_name }}">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <form method="post" action="{% url 'matrimonyApp:exclude_profile' profile.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-primary mt-2">Don't Show</button>
                        </form>
                        <form method="post" action="{% url 'matrimonyApp:save_profile' profile.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-primary mt-2">Save Profile</button>
                        </form>
                        <form method="post" action="{% url 'matrimonyApp:send_request' profile.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-primary mt-2">Send Request</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="container mt-5">
    <h1 class="text-center">No profiles yet.</h1>
</div>
{% endif %}
{% endblock %}